[project]
name = "bria-internal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Bria.ai" }]
maintainers = [
    { name = "omri", email = "omriassa@bria.ai" }
]

requires-python = ">=3.10"
dependencies = []

include = [
    "**/*",
    "!src/**/*_tests.py"
]
#
#[project.scripts]
#test = "pytest ."


[project.optional-dependencies]
redis = [
    "redis>=3.5.3",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/bria_internal"]

[tool.pyright]
include = ["src/bria_internal"]
venvPath = "."
venv = ".venv"
strict = ["src/bria_internal/**/*.py"]

[tool.ruff.lint]
select = ["C4", "E", "F", "I", "PERF", "UP"]
ignore = ["PERF203"]

[tool.ruff]
line-length = 120
target-version = "py310"


[dependency-groups]
dev = [
    "fakeredis>=2.29.0",
    "pyright>=0.0.1",
    "pytest>=8.4.0",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.0",
]

