[project]
name = "bria-internal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "omri", email = "omriassa@bria.ai" }
]
requires-python = ">=3.10"
dependencies = [
    "redis>=6.2.0",
]

include = [
    "src/bria_internal/**/*",
    "!src/bria_internal/**/*_tests.py"
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "fakeredis>=2.29.0",
    "pytest>=8.4.0",
    "pytest-mock>=3.14.1",
]
redis = [
    "redis>=6.2.0",
]
