[project]
name = "bria-sdk"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Bria.ai" }]
maintainers = [
    { name = "omri", email = "omriassa@bria.ai" },
    { name = "noam", email = "noam@bria.ai" }
]

requires-python = ">=3.10"
dependencies = [
    "httpx==0.28.1",
    "pydantic==2.11.10",
    "python_dotenv==1.1.1",
    "pydantic-settings==2.11.0",
    "python_core @ git+https://bar-fingerman-dev:fc9f605912b623be07ebf0eaf32cd83671833a82@github.com/Bria-AI/python_core.git@1.4",
]

include = [
    "**/*",
    "!src/**/*_tests.py"
]


[project.optional-dependencies]
all = [
    "redis>=6.2.0",
    "firebase_admin>=6.4.0",
    "python_core @ git+https://bar-fingerman-dev:fc9f605912b623be07ebf0eaf32cd83671833a82@github.com/Bria-AI/python_core.git@1.4",
    "boto3>=1.34.0",
    "slack_sdk==3.26.1",
    "httpx==0.28.1",
    "pydantic==2.11.10",
    "python_dotenv==1.1.1",
    "pydantic-settings==2.11.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/bria_internal"]


[tool.ruff.lint]
select = ["C4", "E", "F", "I", "PERF", "UP"]
ignore = ["PERF203"]

[tool.ruff]
line-length = 160
target-version = "py310"

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-mock>=3.14.1",
    "ruff>=0.12.0",
]

[tool.pytest.ini_options]
log_cli = true
python_files = "**/*_tests.py"
