name: "Release Version"

on:
  workflow_dispatch:

env:
  PACKAGE_NAME: "bria-sdk"
  OWNER: "Bria.ai"

jobs:
  test:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.10"]
        include:
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: ubuntu-latest
            python-version: "3.12"
          - os: ubuntu-latest
            python-version: "3.13"
    #
    #          - os: windows-latest
    #            python-version: "3.13"
    #          - os: macOS-latest
    #            python-version: "3.13"
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Git authentication
        if: runner.os != 'Windows'
        run: |
          git config --global url."https://${PAT_USER}:${PAT_TOKEN}@github.com/".insteadOf "https://github.com/"
        env:
          PAT_TOKEN: ${{ secrets.OMRI_PAT }}
          PAT_USER: ${{ secrets.OMRI_USER }}
      - name: Set up Git authentication
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git config --global url."https://$Env:PAT_USER:$Env:PAT_TOKEN@github.com/".insteadOf "https://github.com/"
        env:
          PAT_TOKEN: ${{ secrets.OMRI_PAT }}
          PAT_USER: ${{ secrets.OMRI_USER }}
      - name: Show Python version
        run: python --version
      - name: Sync dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -e .
  details:
    name: Get Version
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      new_version: ${{ steps.get_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version' pyproject.toml | head -n 1 | cut -d '"' -f2)
          echo "new_version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "version is: $VERSION"
      - name: Check if tag already exists
        id: tag_exists
        run: |
          TAG="${{ steps.get_version.outputs.new_version }}"
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG$"; then
            echo "Tag $TAG already exists."
            exit 1
          else
            echo "Tag $TAG does not exist."
          fi
  setup_and_build:
    name: Build UV Package
    needs: [details]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # Resolves Python Version from .python-version file if no python-version is provided
        uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Git authentication
        run: |
          git config --global url."https://x-access-token:${PAT_TOKEN}@github.com/".insteadOf "https://github.com/"
        env:
          PAT_TOKEN: ${{ secrets.OMRI_PAT }}
      - name: Debug Git config
        run: git config --get-regexp url
      - name: Install python 3.10
        run: uv python install 3.10
      - name: Install dependencies
        run: uv sync
      - name: Build source and wheel distribution
        run: uv build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  #
  #  pypi_publish:
  #    name: Upload release to PyPI
  #    needs: [setup_and_build, details]
  #    runs-on: ubuntu-latest
  #    environment:
  #      name: release
  #    permissions:
  #      id-token: write
  #    steps:
  #      - name: Download artifacts
  #        uses: actions/download-artifact@v4
  #        with:
  #          name: dist
  #          path: dist/
  #
  #      - name: Install uv
  #        uses: astral-sh/setup-uv@v4
  #
  #      - name: Publish to PyPI
  #        run: uv publish

  github_release:
    name: Create GitHub Release
    needs: [setup_and_build, details]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to avoid issues with tags and branches
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Create GitHub Release
        id: create_release
        run: gh release create ${{ steps.details.outputs.new_version }} dist/* --title ${{ needs.details.outputs.new_version }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
